/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import controller.Gestor;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import model.Equipamento;
import model.Locacao;
import controller.Controlador;
import java.awt.CardLayout;
import java.time.format.DateTimeFormatter;
import model.Cliente;
import service.Relatorio;

/**
 *
 * @author sauls
 */
public class SistemaConstrutecGUI extends javax.swing.JFrame {

    /**
     * Creates new form SistemaConstrutec
     */
    public SistemaConstrutecGUI() {
        initComponents();
        inicializarDropdownEquipamentos();
    }
    
    private Gestor gestor = new Gestor();
    private Controlador controlador = new Controlador();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelComAbas = new javax.swing.JTabbedPane();
        panelCadEquipamentos = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblQuant = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        panelDevoEquip = new javax.swing.JPanel();
        lblBusca = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaBusca = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        btnConfirmar = new javax.swing.JButton();
        btnCancelarDevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        panelGestLocacao = new javax.swing.JPanel();
        lblEquip = new javax.swing.JLabel();
        dropEquip = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        lblDadosCliente = new javax.swing.JLabel();
        lblNomeRegistro = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblNomeRegistro2 = new javax.swing.JLabel();
        txtNomeRegistro = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        lblDatas = new javax.swing.JLabel();
        lblDataTermino = new javax.swing.JLabel();
        lblDataInicio = new javax.swing.JLabel();
        txtDataInicio = new javax.swing.JTextField();
        txtDataTermino = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        btnCancelarReg = new javax.swing.JButton();
        lblMulta = new javax.swing.JLabel();
        txtMulta = new javax.swing.JTextField();
        lblAviso1 = new javax.swing.JLabel();
        lblAviso2 = new javax.swing.JLabel();
        panelRelatorios = new javax.swing.JPanel();
        panelTabelaRelatorios = new javax.swing.JPanel();
        panelEquipMaisAlugados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEquipMaisAlugados = new javax.swing.JTable();
        panelClientesMultas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClientesMultas = new javax.swing.JTable();
        btnEquipMaisAlugados = new javax.swing.JButton();
        btnClientesMultas = new javax.swing.JButton();
        panelEditarDados = new javax.swing.JPanel();
        panelTabelaEditarDados = new javax.swing.JPanel();
        panelEditarEquip = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEditarEquip = new javax.swing.JTable();
        btnAlterarEquip = new javax.swing.JButton();
        btnExcluirEquip = new javax.swing.JButton();
        btnCancelarEditEquip = new javax.swing.JButton();
        lblNomeEdit = new javax.swing.JLabel();
        lblDescricaoEdit = new javax.swing.JLabel();
        lblPrecoEdit = new javax.swing.JLabel();
        lblQuantEdit = new javax.swing.JLabel();
        txtNomeEdit = new javax.swing.JTextField();
        txtDescricaoEdit = new javax.swing.JTextField();
        txtPrecoEdit = new javax.swing.JTextField();
        txtQuantEdit = new javax.swing.JTextField();
        panelEditarClientes = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblEditarClientes = new javax.swing.JTable();
        btnAlterarClientes = new javax.swing.JButton();
        btnExcluirClientes = new javax.swing.JButton();
        btnCancelarEditClientes = new javax.swing.JButton();
        lblNomeEditCliente = new javax.swing.JLabel();
        lblCPFEdit = new javax.swing.JLabel();
        lblTelefoneEdit = new javax.swing.JLabel();
        txtNomeEditClientes = new javax.swing.JTextField();
        txtCPFEdit = new javax.swing.JTextField();
        txtTelefoneEdit = new javax.swing.JTextField();
        panelEditarLocacoes = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblEditarLocacao = new javax.swing.JTable();
        btnAlterarLocacao = new javax.swing.JButton();
        btnExcluirLocacao = new javax.swing.JButton();
        btnCancelarEditLocacao = new javax.swing.JButton();
        lblDataTerminoEdit = new javax.swing.JLabel();
        txtDataTerminoEdit = new javax.swing.JTextField();
        btnEditarEquip = new javax.swing.JButton();
        btnEditarClientes = new javax.swing.JButton();
        btnEditarLocacacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelComAbas.setPreferredSize(new java.awt.Dimension(539, 539));

        lblNome.setText("Nome:");

        lblPreco.setText("Preço Diário:");

        lblDesc.setText("Descrição:");

        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblQuant.setText("Quantidade:");

        txtQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadEquipamentosLayout = new javax.swing.GroupLayout(panelCadEquipamentos);
        panelCadEquipamentos.setLayout(panelCadEquipamentosLayout);
        panelCadEquipamentosLayout.setHorizontalGroup(
            panelCadEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadEquipamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesc)
                    .addComponent(lblPreco)
                    .addComponent(lblQuant)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(panelCadEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCadEquipamentosLayout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPreco)
                    .addComponent(txtDesc)
                    .addComponent(txtNome)
                    .addComponent(txtQuant, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCadEquipamentosLayout.setVerticalGroup(
            panelCadEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadEquipamentosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelCadEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCadEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesc)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCadEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCadEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuant)
                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelCadEquipamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelComAbas.addTab("Cadastro de Equipamentos", panelCadEquipamentos);

        lblBusca.setText("Busca por CPF ou Código de Locação:");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        txaBusca.setColumns(20);
        txaBusca.setRows(5);
        jScrollPane1.setViewportView(txaBusca);

        btnConfirmar.setText("Confirmar Devolução");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelarDevo.setText("Cancelar");
        btnCancelarDevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarDevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDevoEquipLayout = new javax.swing.GroupLayout(panelDevoEquip);
        panelDevoEquip.setLayout(panelDevoEquipLayout);
        panelDevoEquipLayout.setHorizontalGroup(
            panelDevoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator4)
            .addGroup(panelDevoEquipLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarDevo)
                .addGap(76, 76, 76))
            .addGroup(panelDevoEquipLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelDevoEquipLayout.setVerticalGroup(
            panelDevoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDevoEquipLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDevoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusca)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDevoEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelarDevo))
                .addGap(29, 29, 29))
        );

        painelComAbas.addTab("Devolução de Equipamentos", panelDevoEquip);

        lblEquip.setText("Equipamento:");

        dropEquip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dropEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropEquipActionPerformed(evt);
            }
        });

        lblDadosCliente.setText("Dados do Cliente:");

        lblNomeRegistro.setText("Nome:");

        lblCPF.setText("CPF:");

        lblNomeRegistro2.setText("Telefone:");

        lblDatas.setText("Datas:");

        lblDataTermino.setText("Data Término:");

        lblDataInicio.setText("Data Início:");

        txtDataTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataTerminoActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar Locação");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelarReg.setText("Cancelar");
        btnCancelarReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegActionPerformed(evt);
            }
        });

        lblMulta.setText("Valor da Multa:");

        lblAviso1.setText("(O valor da multa será de 10% do valor diário");

        lblAviso2.setText("caso não seja informado)");

        javax.swing.GroupLayout panelGestLocacaoLayout = new javax.swing.GroupLayout(panelGestLocacao);
        panelGestLocacao.setLayout(panelGestLocacaoLayout);
        panelGestLocacaoLayout.setHorizontalGroup(
            panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestLocacaoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarReg)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestLocacaoLayout.createSequentialGroup()
                .addGap(331, 356, Short.MAX_VALUE)
                .addComponent(lblAviso2)
                .addGap(50, 50, 50))
            .addGroup(panelGestLocacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGestLocacaoLayout.createSequentialGroup()
                        .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGestLocacaoLayout.createSequentialGroup()
                                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDadosCliente)
                                    .addComponent(lblNomeRegistro)
                                    .addComponent(lblCPF)
                                    .addComponent(lblNomeRegistro2))
                                .addGap(18, 18, 18)
                                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelGestLocacaoLayout.createSequentialGroup()
                                .addComponent(lblEquip)
                                .addGap(62, 62, 62)
                                .addComponent(dropEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelGestLocacaoLayout.createSequentialGroup()
                        .addComponent(lblMulta)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAviso1))))
            .addGroup(panelGestLocacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGestLocacaoLayout.createSequentialGroup()
                        .addComponent(lblDataTermino)
                        .addGap(18, 18, 18)
                        .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblDatas)
                    .addComponent(lblDataInicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGestLocacaoLayout.setVerticalGroup(
            panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestLocacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEquip)
                    .addComponent(dropEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblDadosCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeRegistro)
                    .addComponent(txtNomeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeRegistro2)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(lblDatas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGestLocacaoLayout.createSequentialGroup()
                        .addComponent(lblDataInicio)
                        .addGap(9, 9, 9)
                        .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataTermino)
                            .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelGestLocacaoLayout.createSequentialGroup()
                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMulta)
                    .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAviso1)
                        .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAviso2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestLocacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelarReg))
                .addGap(18, 18, 18))
        );

        painelComAbas.addTab("Registro de Locações", panelGestLocacao);

        panelTabelaRelatorios.setLayout(new java.awt.CardLayout());

        tblEquipMaisAlugados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Código", "Aluguéis", "Receita Total"
            }
        ));
        jScrollPane2.setViewportView(tblEquipMaisAlugados);

        javax.swing.GroupLayout panelEquipMaisAlugadosLayout = new javax.swing.GroupLayout(panelEquipMaisAlugados);
        panelEquipMaisAlugados.setLayout(panelEquipMaisAlugadosLayout);
        panelEquipMaisAlugadosLayout.setHorizontalGroup(
            panelEquipMaisAlugadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelEquipMaisAlugadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEquipMaisAlugadosLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelEquipMaisAlugadosLayout.setVerticalGroup(
            panelEquipMaisAlugadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelEquipMaisAlugadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEquipMaisAlugadosLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        panelTabelaRelatorios.add(panelEquipMaisAlugados, "equipamentos");

        tblClientesMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cliente", "CPF", "Multas"
            }
        ));
        jScrollPane3.setViewportView(tblClientesMultas);

        javax.swing.GroupLayout panelClientesMultasLayout = new javax.swing.GroupLayout(panelClientesMultas);
        panelClientesMultas.setLayout(panelClientesMultasLayout);
        panelClientesMultasLayout.setHorizontalGroup(
            panelClientesMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelClientesMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesMultasLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelClientesMultasLayout.setVerticalGroup(
            panelClientesMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelClientesMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelClientesMultasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelTabelaRelatorios.add(panelClientesMultas, "multas");

        btnEquipMaisAlugados.setText("Equipamentos Mais Alugados");
        btnEquipMaisAlugados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquipMaisAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipMaisAlugadosActionPerformed(evt);
            }
        });

        btnClientesMultas.setText("Clientes com Multas Acumuladas");
        btnClientesMultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientesMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesMultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRelatoriosLayout = new javax.swing.GroupLayout(panelRelatorios);
        panelRelatorios.setLayout(panelRelatoriosLayout);
        panelRelatoriosLayout.setHorizontalGroup(
            panelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatoriosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRelatoriosLayout.createSequentialGroup()
                        .addComponent(btnEquipMaisAlugados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClientesMultas))
                    .addComponent(panelTabelaRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        panelRelatoriosLayout.setVerticalGroup(
            panelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientesMultas)
                    .addComponent(btnEquipMaisAlugados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabelaRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelComAbas.addTab("Relatórios", panelRelatorios);

        panelTabelaEditarDados.setLayout(new java.awt.CardLayout());

        tblEditarEquip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Preço Diário", "Quantidade"
            }
        ));
        jScrollPane4.setViewportView(tblEditarEquip);

        btnAlterarEquip.setText("Alterar");

        btnExcluirEquip.setText("Excluir");

        btnCancelarEditEquip.setText("Cancelar");

        lblNomeEdit.setText("Nome:");

        lblDescricaoEdit.setText("Descrição:");

        lblPrecoEdit.setText("Preço Diário:");

        lblQuantEdit.setText("Quantidade:");

        txtNomeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditarEquipLayout = new javax.swing.GroupLayout(panelEditarEquip);
        panelEditarEquip.setLayout(panelEditarEquipLayout);
        panelEditarEquipLayout.setHorizontalGroup(
            panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarEquipLayout.createSequentialGroup()
                .addGroup(panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditarEquipLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnAlterarEquip)
                        .addGap(120, 120, 120)
                        .addComponent(btnExcluirEquip)
                        .addGap(126, 126, 126)
                        .addComponent(btnCancelarEditEquip))
                    .addGroup(panelEditarEquipLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEditarEquipLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeEdit)
                                    .addComponent(lblDescricaoEdit)
                                    .addComponent(lblPrecoEdit)
                                    .addComponent(lblQuantEdit))
                                .addGap(31, 31, 31)
                                .addGroup(panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomeEdit)
                                    .addComponent(txtDescricaoEdit)
                                    .addComponent(txtPrecoEdit)
                                    .addComponent(txtQuantEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEditarEquipLayout.setVerticalGroup(
            panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarEquipLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEdit)
                    .addComponent(txtNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoEdit)
                    .addComponent(txtDescricaoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoEdit)
                    .addComponent(txtPrecoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantEdit)
                    .addComponent(txtQuantEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panelEditarEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarEquip)
                    .addComponent(btnExcluirEquip)
                    .addComponent(btnCancelarEditEquip)))
        );

        panelTabelaEditarDados.add(panelEditarEquip, "card2");

        tblEditarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Telefone"
            }
        ));
        jScrollPane5.setViewportView(tblEditarClientes);

        btnAlterarClientes.setText("Alterar");

        btnExcluirClientes.setText("Excluir");

        btnCancelarEditClientes.setText("Cancelar");

        lblNomeEditCliente.setText("Nome:");

        lblCPFEdit.setText("CPF:");

        lblTelefoneEdit.setText("Telefone:");

        txtNomeEditClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEditClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditarClientesLayout = new javax.swing.GroupLayout(panelEditarClientes);
        panelEditarClientes.setLayout(panelEditarClientesLayout);
        panelEditarClientesLayout.setHorizontalGroup(
            panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarClientesLayout.createSequentialGroup()
                .addGroup(panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditarClientesLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnAlterarClientes)
                        .addGap(120, 120, 120)
                        .addComponent(btnExcluirClientes)
                        .addGap(126, 126, 126)
                        .addComponent(btnCancelarEditClientes))
                    .addGroup(panelEditarClientesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEditarClientesLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeEditCliente)
                                    .addComponent(lblCPFEdit)
                                    .addComponent(lblTelefoneEdit))
                                .addGap(48, 48, 48)
                                .addGroup(panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomeEditClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtCPFEdit)
                                    .addComponent(txtTelefoneEdit))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEditarClientesLayout.setVerticalGroup(
            panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarClientesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEditCliente)
                    .addComponent(txtNomeEditClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFEdit)
                    .addComponent(txtCPFEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneEdit)
                    .addComponent(txtTelefoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarClientes)
                    .addComponent(btnExcluirClientes)
                    .addComponent(btnCancelarEditClientes)))
        );

        panelTabelaEditarDados.add(panelEditarClientes, "card3");

        tblEditarLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Preço Diário", "Quantidade"
            }
        ));
        jScrollPane6.setViewportView(tblEditarLocacao);

        btnAlterarLocacao.setText("Alterar");

        btnExcluirLocacao.setText("Excluir");

        btnCancelarEditLocacao.setText("Cancelar");

        lblDataTerminoEdit.setText("Data Término:");

        txtDataTerminoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataTerminoEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditarLocacoesLayout = new javax.swing.GroupLayout(panelEditarLocacoes);
        panelEditarLocacoes.setLayout(panelEditarLocacoesLayout);
        panelEditarLocacoesLayout.setHorizontalGroup(
            panelEditarLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLocacoesLayout.createSequentialGroup()
                .addGroup(panelEditarLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditarLocacoesLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnAlterarLocacao)
                        .addGap(120, 120, 120)
                        .addComponent(btnExcluirLocacao)
                        .addGap(126, 126, 126)
                        .addComponent(btnCancelarEditLocacao))
                    .addGroup(panelEditarLocacoesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelEditarLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEditarLocacoesLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblDataTerminoEdit)
                                .addGap(31, 31, 31)
                                .addComponent(txtDataTerminoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelEditarLocacoesLayout.setVerticalGroup(
            panelEditarLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLocacoesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelEditarLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataTerminoEdit)
                    .addComponent(txtDataTerminoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panelEditarLocacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarLocacao)
                    .addComponent(btnExcluirLocacao)
                    .addComponent(btnCancelarEditLocacao)))
        );

        panelTabelaEditarDados.add(panelEditarLocacoes, "card4");

        btnEditarEquip.setText("Editar Equipamentos");

        btnEditarClientes.setText("Editar Clientes");

        btnEditarLocacacoes.setText("Editar Locações");

        javax.swing.GroupLayout panelEditarDadosLayout = new javax.swing.GroupLayout(panelEditarDados);
        panelEditarDados.setLayout(panelEditarDadosLayout);
        panelEditarDadosLayout.setHorizontalGroup(
            panelEditarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditarDadosLayout.createSequentialGroup()
                        .addComponent(panelTabelaEditarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelEditarDadosLayout.createSequentialGroup()
                        .addComponent(btnEditarEquip)
                        .addGap(69, 69, 69)
                        .addComponent(btnEditarClientes)
                        .addGap(90, 90, 90)
                        .addComponent(btnEditarLocacacoes)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        panelEditarDadosLayout.setVerticalGroup(
            panelEditarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarDadosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelEditarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarEquip)
                    .addComponent(btnEditarClientes)
                    .addComponent(btnEditarLocacacoes))
                .addGap(27, 27, 27)
                .addComponent(panelTabelaEditarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        painelComAbas.addTab("Editar Dados", panelEditarDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelComAbas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelComAbas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void dropEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropEquipActionPerformed

    }//GEN-LAST:event_dropEquipActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnEquipMaisAlugadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipMaisAlugadosActionPerformed
        CardLayout card = (CardLayout)panelTabelaRelatorios.getLayout();
        card.show(panelTabelaRelatorios, "equipamentos");
    }//GEN-LAST:event_btnEquipMaisAlugadosActionPerformed

    private void txtQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //O Botão registra os equipamentos se as informações estiverem corretas
        try {
            String nome = txtNome.getText();
            String descricao = txtDesc.getText();
            double valorDiario = Double.parseDouble(txtPreco.getText());
            int quantidade = Integer.parseInt(txtQuant.getText());

            gestor.cadastrarEquipamento(nome, descricao, valorDiario, quantidade);

            JOptionPane.showMessageDialog(this, "Equipamento cadastrado com sucesso!");
            inicializarDropdownEquipamentos();
            limparCamposCadastro();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Preencha os campos corretamente!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    //Método de limpar os campos da tela de cadastro
    private void limparCamposCadastro() {
        txtNome.setText("");
        txtDesc.setText("");
        txtPreco.setText("");
        txtQuant.setText("");
    }
    
    //Método de limpar os campos da tela de registro
    private void limparCamposRegistro() {
        txtNomeRegistro.setText("");
        txtCPF.setText("");
        txtTelefone.setText("");
        txtDataInicio.setText("");
        txtDataTermino.setText("");
        txtMulta.setText("");
    }
    
    //Método que inicia o dropdown da tela de locação
    private void inicializarDropdownEquipamentos() {
        //Esvazia o dropdown
        dropEquip.removeAllItems();

        //Coloca esta opção no dropdown
        dropEquip.addItem("Selecione uma opção");

        //Quando um equipamento é registrado ele é automaticamente adicionado às opções do dropdown
        List<Equipamento> equipamentosDisponiveis = gestor.getEquipamentosDisponiveis();
        for (Equipamento equipamento : equipamentosDisponiveis) {
            dropEquip.addItem(equipamento.getNome());
        }

        //Garante que "Selecione uma opção" seja a primeira escolha do dropdown
        dropEquip.setSelectedIndex(0);
    }


    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCamposCadastro();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarDevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDevoActionPerformed
        txtBuscar.setText("");
    }//GEN-LAST:event_btnCancelarDevoActionPerformed

    private void btnCancelarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegActionPerformed
        limparCamposRegistro();
    }//GEN-LAST:event_btnCancelarRegActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
            try {
            String nomeCliente = txtNomeRegistro.getText().trim();
            String cpf = txtCPF.getText().trim();
            String telefone = txtTelefone.getText().trim();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dataInicio = LocalDate.parse(txtDataInicio.getText().trim(), formatter);
            LocalDate dataFim = LocalDate.parse(txtDataTermino.getText().trim(), formatter);
            double multaPercentual = txtMulta.getText().isEmpty() ? 10.0 : Double.parseDouble(txtMulta.getText());

            // Validação de campos obrigatórios
            if (nomeCliente.isEmpty() || cpf.isEmpty() || telefone.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validação: Nome deve conter apenas letras e espaços
            if (!nomeCliente.matches("[A-Za-zÀ-ÖØ-öø-ÿ ]+")) {
                JOptionPane.showMessageDialog(this, "Nome inválido! Digite apenas letras.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validação: CPF deve conter apenas números e ter 11 dígitos
            if (!cpf.matches("\\d{11}")) {
                JOptionPane.showMessageDialog(this, "CPF inválido! Deve conter exatamente 11 números.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validação: Telefone deve conter apenas números e ter entre 10 e 11 dígitos
            if (!telefone.matches("\\d{10,11}")) {
                JOptionPane.showMessageDialog(this, "Telefone inválido! Deve conter apenas números (DDD + número).", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //Seleciona o equipamento no dropdown
            int selectedIndex = dropEquip.getSelectedIndex();
            if (selectedIndex <= 0) {
                JOptionPane.showMessageDialog(this, "Selecione um equipamento para a locação.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Equipamento equipamentoSelecionado = gestor.getEquipamentosDisponiveis().get(selectedIndex - 1);

            //Registra a locação
            gestor.registrarLocacao(nomeCliente, cpf, telefone, List.of(equipamentoSelecionado), dataInicio, dataFim, multaPercentual);

            JOptionPane.showMessageDialog(this, "Locação registrada com sucesso!");

            //Limpa os campos
            limparCamposRegistro();
            inicializarDropdownEquipamentos(); //Atualiza o dropdown após a locação
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao registrar locação: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); //Para depuração
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtDataTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataTerminoActionPerformed

    private void btnClientesMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesMultasActionPerformed
        CardLayout card = (CardLayout)panelTabelaRelatorios.getLayout();
        card.show(panelTabelaRelatorios, "multas");
    }//GEN-LAST:event_btnClientesMultasActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String cpfOuCodigo = txtBuscar.getText().trim();

        if (cpfOuCodigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um CPF ou Código de Locação válido.", 
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Buscar locações pelo CPF
        List<Locacao> locacoes = gestor.buscarLocacaoPorCpf(cpfOuCodigo);

        if (locacoes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma locação encontrada para o CPF fornecido.", 
                                          "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Suponha que a interface tenha uma forma de selecionar uma locação específica (por exemplo, um dropdown)
        Locacao locacaoSelecionada = locacoes.get(0); //Para simplificação, pegue a primeira locação encontrada

        //Registra a devolução
        LocalDate dataDevolucao = LocalDate.now();
        gestor.registrarDevolucao(locacaoSelecionada, dataDevolucao);

        //Atualiza a tela com os detalhes da devolução
        StringBuilder detalhesDevolucao = new StringBuilder();
        detalhesDevolucao.append("Equipamento(s) Devolvido(s):\n");

        for (Equipamento equipamento : locacaoSelecionada.getEquipamentos()) {
            detalhesDevolucao.append(String.format("- %s (Código: %s)\n", equipamento.getNome(), equipamento.getCodigo()));
        }

        //Detalhes imprimidos na tela
        detalhesDevolucao.append("\nResumo da Devolução:\n");
        detalhesDevolucao.append(String.format("Data de Término: %s\n", locacaoSelecionada.getDataTermino()));
        detalhesDevolucao.append(String.format("Data de Devolução: %s\n", dataDevolucao));
        detalhesDevolucao.append(String.format("Multa Aplicada: R$ %.2f\n", locacaoSelecionada.calcularMulta(dataDevolucao)));
        detalhesDevolucao.append(String.format("Valor do Aluguel: R$ %.2f\n", locacaoSelecionada.getValorTotal()));
        detalhesDevolucao.append(String.format("Valor Total (Aluguel + Multa): R$ %.2f\n", 
                                               locacaoSelecionada.getValorTotal() + locacaoSelecionada.calcularMulta(dataDevolucao)));

        txaBusca.setText(detalhesDevolucao.toString());
        
        inicializarDropdownEquipamentos();

        //Confirmação visual
        JOptionPane.showMessageDialog(this, "Devolução confirmada com sucesso!", 
                                      "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNomeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEditActionPerformed

    private void txtNomeEditClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEditClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEditClientesActionPerformed

    private void txtDataTerminoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataTerminoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataTerminoEditActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaConstrutecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaConstrutecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaConstrutecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaConstrutecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaConstrutecGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarClientes;
    private javax.swing.JButton btnAlterarEquip;
    private javax.swing.JButton btnAlterarLocacao;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarDevo;
    private javax.swing.JButton btnCancelarEditClientes;
    private javax.swing.JButton btnCancelarEditEquip;
    private javax.swing.JButton btnCancelarEditLocacao;
    private javax.swing.JButton btnCancelarReg;
    private javax.swing.JButton btnClientesMultas;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditarClientes;
    private javax.swing.JButton btnEditarEquip;
    private javax.swing.JButton btnEditarLocacacoes;
    private javax.swing.JButton btnEquipMaisAlugados;
    private javax.swing.JButton btnExcluirClientes;
    private javax.swing.JButton btnExcluirEquip;
    private javax.swing.JButton btnExcluirLocacao;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> dropEquip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAviso1;
    private javax.swing.JLabel lblAviso2;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPFEdit;
    private javax.swing.JLabel lblDadosCliente;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblDataTermino;
    private javax.swing.JLabel lblDataTerminoEdit;
    private javax.swing.JLabel lblDatas;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDescricaoEdit;
    private javax.swing.JLabel lblEquip;
    private javax.swing.JLabel lblMulta;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeEdit;
    private javax.swing.JLabel lblNomeEditCliente;
    private javax.swing.JLabel lblNomeRegistro;
    private javax.swing.JLabel lblNomeRegistro2;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblPrecoEdit;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JLabel lblQuantEdit;
    private javax.swing.JLabel lblTelefoneEdit;
    private javax.swing.JTabbedPane painelComAbas;
    private javax.swing.JPanel panelCadEquipamentos;
    private javax.swing.JPanel panelClientesMultas;
    private javax.swing.JPanel panelDevoEquip;
    private javax.swing.JPanel panelEditarClientes;
    private javax.swing.JPanel panelEditarDados;
    private javax.swing.JPanel panelEditarEquip;
    private javax.swing.JPanel panelEditarLocacoes;
    private javax.swing.JPanel panelEquipMaisAlugados;
    private javax.swing.JPanel panelGestLocacao;
    private javax.swing.JPanel panelRelatorios;
    private javax.swing.JPanel panelTabelaEditarDados;
    private javax.swing.JPanel panelTabelaRelatorios;
    private javax.swing.JTable tblClientesMultas;
    private javax.swing.JTable tblEditarClientes;
    private javax.swing.JTable tblEditarEquip;
    private javax.swing.JTable tblEditarLocacao;
    private javax.swing.JTable tblEquipMaisAlugados;
    private javax.swing.JTextArea txaBusca;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCPFEdit;
    private javax.swing.JTextField txtDataInicio;
    private javax.swing.JTextField txtDataTermino;
    private javax.swing.JTextField txtDataTerminoEdit;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtDescricaoEdit;
    private javax.swing.JTextField txtMulta;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeEdit;
    private javax.swing.JTextField txtNomeEditClientes;
    private javax.swing.JTextField txtNomeRegistro;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtPrecoEdit;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtQuantEdit;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTelefoneEdit;
    // End of variables declaration//GEN-END:variables
}